---
- name: Wait for ssh connection
  hosts: all
  gather_facts: False
  tasks:
    - name: Ensure ssh port open
      wait_for:
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python2

- name: Install python3, docker and docker-compose
  hosts: all
  become: yes
  become_user: root
  gather_facts: False
  tasks:
    - name: Make sure python3 and docker are installed
      vars: 
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.14.0/docker-compose-linux-{{lookup('pipe','uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Ensure docker is running
      systemd:
        name: docker
        state: started
    - name: Install docker python module
      pip:
        name: 
          - docker
          - docker-compose

- name: Create linux user
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Create new linux user
      user:
        name: josmbrio
        groups: adm,docker
- name: Start docker containers
  hosts: all
  become: yes
  become_user: josmbrio
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker compose
      copy:
        src: ./docker-compose.yaml
        dest: /home/josmbrio/docker-compose.yaml
    - name: Docker login
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: josmbrio
        password: "{{docker_password}}"
    - name: Start container from compose
      docker_compose:
        project_src: /home/josmbrio
        state: present # docker-compose up